### ISSUE TITLE
mac cargo install 失败

### ISSUE THREAD

**Issue by zxconan** [Tamschi/reserde#20]
🕙 17:05:31 ❯ cargo install --git https://github.com/Tamschi/reserde.git
    Updating git repository `https://github.com/Tamschi/reserde.git`
  Installing reserde v0.0.2 (https://github.com/Tamschi/reserde.git#7fb04fd9)
    Updating `rustcc` index
  Downloaded ciborium v0.1.0 (registry `rustcc`)
  Downloaded 1 crate (24.1 KB) in 1.55s
   Compiling proc-macro2 v1.0.29
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.76
   Compiling serde_derive v1.0.130
   Compiling serde v1.0.130
   Compiling version_check v0.9.3
   Compiling proc-macro-hack v0.5.19
   Compiling autocfg v1.0.1
   Compiling unicode-segmentation v1.8.0
   Compiling hashbrown v0.11.2
   Compiling utf8-ranges v1.0.4
   Compiling regex-syntax v0.6.25
   Compiling static_assertions v1.1.0
   Compiling fnv v1.0.7
   Compiling ryu v1.0.5
   Compiling beef v0.5.1
   Compiling wyz v0.2.0
   Compiling gnaw v0.0.2
   Compiling memchr v2.4.1
   Compiling cervine v0.0.6
   Compiling lazy_static v1.4.0
   Compiling tap v1.0.1
   Compiling itoa v0.4.8
   Compiling argh_shared v0.1.6
   Compiling enum_properties v0.3.0
   Compiling linked-hash-map v0.5.4
   Compiling percent-encoding v2.1.0
   Compiling serde_json v1.0.67
   Compiling debugless-unwrap v0.0.4
   Compiling matches v0.1.9
   Compiling joinery v2.1.0
   Compiling paste v1.0.5
   Compiling either v1.6.1
   Compiling half v1.7.1
   Compiling dtoa v0.4.8
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.7.0
   Compiling smartstring v0.2.9
   Compiling heck v0.3.3
   Compiling form_urlencoded v1.0.1
   Compiling yaml-rust v0.4.5
   Compiling lazy-transform-str v0.0.6
   Compiling quote v1.0.9
   Compiling try_match_inner v0.2.0
   Compiling logos-derive v0.12.0
   Compiling linkme-impl v0.2.6
   Compiling argh_derive v0.1.6
   Compiling strum_macros v0.21.1
   Compiling linkme v0.2.6
   Compiling try_match v0.2.2
   Compiling argh v0.1.6
   Compiling strum v0.21.0
   Compiling logos v0.12.0
   Compiling taml v0.0.11
   Compiling serde_bytes v0.11.5
   Compiling serde-object v0.0.0-alpha.0
   Compiling scientific v0.1.2
   Compiling quick-xml v0.22.0
   Compiling bincode v1.3.3
   Compiling serde_yaml v0.8.20
   Compiling serde-detach v0.0.1
   Compiling serde_urlencoded v0.7.0
   Compiling ciborium v0.1.0
   Compiling serde_bencode v0.2.3
   Compiling serde_taml v0.0.3
LLVM ERROR: Global variable '_ZN10serde_taml2de11enum_access19ENUM_VARIANT_ASSIST17hd6ae3fd371d18d26E' has an invalid section specifier '__DATA,__ENUM_VARIANT_ASSISTS': mach-o section specifier requires a section whose length is between 1 and 16 characters.
error: could not compile `serde_taml`
warning: build failed, waiting for other jobs to finish...
error: failed to compile `reserde v0.0.2 (https://github.com/Tamschi/reserde.git#7fb04fd9)`, intermediate artifacts can be found at `/var/folders/1p/d279ykmj2173gs0ybf1v6fjc0000gn/T/cargo-installphfWm7`

Caused by:
  build failed

~ via 🎯 v2.12.3 via ☕ v11.0.10
🕙 17:08:24 ❯ cargo -V
cargo 1.56.0-nightly (18751dd3f 2021-09-01)

~ via 🎯 v2.12.3 via ☕ v11.0.10
🕙 17:08:57 ❯ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/xinzhang/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.57.0-nightly (fdf65053e 2021-09-07)

**Comment by Tamschi** [comment]
Sorry for not replying earlier, I somehow missed this.

The good news is that this was most likely an issue in `linkme` that was fixed about a week ago:
https://github.com/dtolnay/linkme/issues/35
https://github.com/dtolnay/linkme/releases/tag/0.2.7

I incidentally updated _Cargo.lock_ in this regard a little earlier, and just ran and committed `cargo update` for good measure, so the installation should work now.

Please let me know if this solves the problem, as I don't have an Apple device to test this with.

**Comment by Tamschi** [comment]
I will close this for now, since I'm *pretty sure* the issue has been fixed. Don't hesitate to reopen if it hasn't.
I'll also publish a new release today to (among other reasons) make sure you can install directly from Crates.io.
